-- Pavilion Fabrication Tracker V4
-- Run this once in Supabase SQL Editor.
-- This first team version intentionally uses link-based collaboration:
-- anyone who can load the web app and its publishable key can read/write tracker data.
-- For a public-facing deployment, switch to Supabase Auth + user-specific RLS policies.

create table if not exists public.pavilion_parts (
  project_id text not null default 'pavilion-2026',
  rhino_guid text not null,
  object_id text,
  module_no integer,
  level integer,
  sequence integer,
  rhino_object_name text,
  material text,
  material_details text,
  manufacturing_method text,
  assigned_to text,
  structural_status text,
  compression_force_kn numeric,
  ready_for_production text,
  infill_pattern text,
  infill_density_pct numeric,
  weight_kg numeric,
  production_status text,
  drying_qc_status text,
  construction_status text,
  overall_status text,
  machine text,
  gcode_file text,
  notes text,
  updated_by text,
  updated_at timestamptz not null default now(),
  primary key (project_id, rhino_guid)
);

create index if not exists pavilion_parts_object_id_idx
  on public.pavilion_parts(project_id, object_id);
create index if not exists pavilion_parts_updated_at_idx
  on public.pavilion_parts(project_id, updated_at desc);

alter table public.pavilion_parts enable row level security;

drop policy if exists "pavilion parts readable" on public.pavilion_parts;
create policy "pavilion parts readable"
on public.pavilion_parts for select
to anon, authenticated
using (true);

drop policy if exists "pavilion parts insertable" on public.pavilion_parts;
create policy "pavilion parts insertable"
on public.pavilion_parts for insert
to anon, authenticated
with check (true);

drop policy if exists "pavilion parts updateable" on public.pavilion_parts;
create policy "pavilion parts updateable"
on public.pavilion_parts for update
to anon, authenticated
using (true)
with check (true);

create table if not exists public.pavilion_history (
  id bigint generated by default as identity primary key,
  project_id text not null,
  rhino_guid text not null,
  object_id text,
  updated_by text,
  changed_at timestamptz not null default now(),
  record_snapshot jsonb not null
);

create index if not exists pavilion_history_lookup_idx
  on public.pavilion_history(project_id, rhino_guid, changed_at desc);

alter table public.pavilion_history enable row level security;

drop policy if exists "pavilion history readable" on public.pavilion_history;
create policy "pavilion history readable"
on public.pavilion_history for select
to anon, authenticated
using (true);

create or replace function public.log_pavilion_part_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.pavilion_history(project_id, rhino_guid, object_id, updated_by, record_snapshot)
  values(new.project_id, new.rhino_guid, new.object_id, coalesce(new.updated_by,'Unidentified'), to_jsonb(new));
  return new;
end;
$$;

drop trigger if exists pavilion_part_history_trigger on public.pavilion_parts;
create trigger pavilion_part_history_trigger
after insert or update on public.pavilion_parts
for each row execute function public.log_pavilion_part_change();

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'pavilion_parts'
  ) then
    alter publication supabase_realtime add table public.pavilion_parts;
  end if;
end $$;


-- Shared tracker UI settings
create table if not exists public.pavilion_settings (
  project_id text primary key,
  color_overrides jsonb not null default '{}'::jsonb,
  updated_by text,
  updated_at timestamptz not null default now()
);

alter table public.pavilion_settings enable row level security;

drop policy if exists "pavilion_settings_select" on public.pavilion_settings;
create policy "pavilion_settings_select"
on public.pavilion_settings for select
to anon, authenticated
using (true);

drop policy if exists "pavilion_settings_insert" on public.pavilion_settings;
create policy "pavilion_settings_insert"
on public.pavilion_settings for insert
to anon, authenticated
with check (true);

drop policy if exists "pavilion_settings_update" on public.pavilion_settings;
create policy "pavilion_settings_update"
on public.pavilion_settings for update
to anon, authenticated
using (true)
with check (true);


-- Per-module site photos / short notes
create table if not exists public.pavilion_module_photos (
  id bigint generated by default as identity primary key,
  project_id text not null,
  rhino_guid text not null,
  object_id text,
  storage_path text not null unique,
  note text not null default '' check (char_length(note) <= 240),
  uploaded_by text,
  created_at timestamptz not null default now()
);

create index if not exists pavilion_module_photos_lookup_idx
  on public.pavilion_module_photos(project_id, rhino_guid, created_at desc);

alter table public.pavilion_module_photos enable row level security;

drop policy if exists "pavilion_module_photos_select" on public.pavilion_module_photos;
create policy "pavilion_module_photos_select"
on public.pavilion_module_photos for select
to anon, authenticated
using (true);

drop policy if exists "pavilion_module_photos_insert" on public.pavilion_module_photos;
create policy "pavilion_module_photos_insert"
on public.pavilion_module_photos for insert
to anon, authenticated
with check (
  project_id = 'pavilion-2026'
  and char_length(coalesce(uploaded_by,'')) between 1 and 80
  and char_length(coalesce(note,'')) <= 240
);

create or replace function public.limit_pavilion_module_photos()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (
    select count(*)
    from public.pavilion_module_photos
    where project_id = new.project_id
      and rhino_guid = new.rhino_guid
  ) >= 5 then
    raise exception 'Maximum 5 photos per module';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_limit_pavilion_module_photos on public.pavilion_module_photos;
create trigger trg_limit_pavilion_module_photos
before insert on public.pavilion_module_photos
for each row execute function public.limit_pavilion_module_photos();
