create table if not exists public.pavilion_module_photos (
  id bigint generated by default as identity primary key,
  project_id text not null,
  rhino_guid text not null,
  object_id text,
  storage_path text not null unique,
  note text not null default '' check (char_length(note) <= 240),
  uploaded_by text,
  created_at timestamptz not null default now()
);

create index if not exists pavilion_module_photos_lookup_idx
  on public.pavilion_module_photos(project_id, rhino_guid, created_at desc);

alter table public.pavilion_module_photos enable row level security;

drop policy if exists "pavilion_module_photos_select" on public.pavilion_module_photos;
create policy "pavilion_module_photos_select"
on public.pavilion_module_photos for select
to anon, authenticated
using (true);

drop policy if exists "pavilion_module_photos_insert" on public.pavilion_module_photos;
create policy "pavilion_module_photos_insert"
on public.pavilion_module_photos for insert
to anon, authenticated
with check (
  project_id = 'pavilion-2026'
  and char_length(coalesce(uploaded_by,'')) between 1 and 80
  and char_length(coalesce(note,'')) <= 240
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'pavilion-module-photos',
  'pavilion-module-photos',
  true,
  2097152,
  array['image/jpeg','image/webp','image/png']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "pavilion_module_photo_upload" on storage.objects;
create policy "pavilion_module_photo_upload"
on storage.objects for insert
to anon, authenticated
with check (
  bucket_id = 'pavilion-module-photos'
  and (storage.foldername(name))[1] = 'pavilion-2026'
);

do $$
begin
  alter publication supabase_realtime add table public.pavilion_module_photos;
exception
  when duplicate_object then null;
end $$;
